// used to export an instance of the factory bytecode and interface in order to use the methods inside the application

import web3 from "./web3";
import ElectionFactory from "./build/ElectionFactory.json";

const instance = new web3.eth.Contract(
  JSON.parse(ElectionFactory.interface),
  "0xC330FEFC623eC52855d7c045200764406b6139b9" // Change this line to add the contract address generated by the script npm run deploy
);

export default instance;
